### ISSUE TITLE
Suggestion: Added Phone Number and changing color

### ISSUE THREAD

**Issue by demoGA1** [SuryaVelmurugesan/Sample_web#1]
I think its better to add phone number in the Contact Me section
& the color of p tag should be changed

The changed code look like this :

```css
p {
   color: aqua;
}
```
